# frozen_string_literal: true

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: xds/annotations/v3/status.proto

require "google/protobuf"

require "google/protobuf/descriptor_pb"


descriptor_data = "\n\x1fxds/annotations/v3/status.proto\x12\x12xds.annotations.v3\x1a google/protobuf/descriptor.proto\"0\n\x14\x46ileStatusAnnotation\x12\x18\n\x10work_in_progress\x18\x01 \x01(\x08\"3\n\x17MessageStatusAnnotation\x12\x18\n\x10work_in_progress\x18\x01 \x01(\x08\"1\n\x15\x46ieldStatusAnnotation\x12\x18\n\x10work_in_progress\x18\x01 \x01(\x08\"v\n\x10StatusAnnotation\x12\x18\n\x10work_in_progress\x18\x01 \x01(\x08\x12H\n\x16package_version_status\x18\x02 \x01(\x0e\x32(.xds.annotations.v3.PackageVersionStatus*]\n\x14PackageVersionStatus\x12\x0b\n\x07UNKNOWN\x10\x00\x12\n\n\x06\x46ROZEN\x10\x01\x12\n\n\x06\x41\x43TIVE\x10\x02\x12 \n\x1cNEXT_MAJOR_VERSION_CANDIDATE\x10\x03:^\n\x0b\x66ile_status\x12\x1c.google.protobuf.FileOptions\x18\xea\xc8\x94l \x01(\x0b\x32(.xds.annotations.v3.FileStatusAnnotation:g\n\x0emessage_status\x12\x1f.google.protobuf.MessageOptions\x18\xea\xc8\x94l \x01(\x0b\x32+.xds.annotations.v3.MessageStatusAnnotation:a\n\x0c\x66ield_status\x12\x1d.google.protobuf.FieldOptions\x18\xea\xc8\x94l \x01(\x0b\x32).xds.annotations.v3.FieldStatusAnnotationB+Z)github.com/cncf/xds/go/xds/annotations/v3b\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Xds
	module Annotations
		module V3
			FileStatusAnnotation = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("xds.annotations.v3.FileStatusAnnotation").msgclass
			MessageStatusAnnotation = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("xds.annotations.v3.MessageStatusAnnotation").msgclass
			FieldStatusAnnotation = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("xds.annotations.v3.FieldStatusAnnotation").msgclass
			StatusAnnotation = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("xds.annotations.v3.StatusAnnotation").msgclass
			PackageVersionStatus = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("xds.annotations.v3.PackageVersionStatus").enummodule
		end
	end
end
