# frozen_string_literal: true

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: xds/core/v3/authority.proto

require "google/protobuf"

require "xds/annotations/v3/status_pb"
require "validate/validate_pb"


descriptor_data = "\n\x1bxds/core/v3/authority.proto\x12\x0bxds.core.v3\x1a\x1fxds/annotations/v3/status.proto\x1a\x17validate/validate.proto\"\"\n\tAuthority\x12\x15\n\x04name\x18\x01 \x01(\tB\x07\xfa\x42\x04r\x02\x10\x01\x42V\n\x16\x63om.github.xds.core.v3B\x0e\x41uthorityProtoP\x01Z\"github.com/cncf/xds/go/xds/core/v3\xd2\xc6\xa4\xe1\x06\x02\x08\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Xds
		module Core
				module V3
						Authority = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("xds.core.v3.Authority").msgclass
				end
		end
end
