# frozen_string_literal: true

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: xds/core/v3/context_params.proto

require "google/protobuf"

require "xds/annotations/v3/status_pb"


descriptor_data = "\n xds/core/v3/context_params.proto\x12\x0bxds.core.v3\x1a\x1fxds/annotations/v3/status.proto\"v\n\rContextParams\x12\x36\n\x06params\x18\x01 \x03(\x0b\x32&.xds.core.v3.ContextParams.ParamsEntry\x1a-\n\x0bParamsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42Z\n\x16\x63om.github.xds.core.v3B\x12\x43ontextParamsProtoP\x01Z\"github.com/cncf/xds/go/xds/core/v3\xd2\xc6\xa4\xe1\x06\x02\x08\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Xds
		module Core
				module V3
						ContextParams = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("xds.core.v3.ContextParams").msgclass
				end
		end
end
