# frozen_string_literal: true

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: xds/core/v3/extension.proto

require "google/protobuf"

require "validate/validate_pb"
require "google/protobuf/any_pb"


descriptor_data = "\n\x1bxds/core/v3/extension.proto\x12\x0bxds.core.v3\x1a\x17validate/validate.proto\x1a\x19google/protobuf/any.proto\"c\n\x14TypedExtensionConfig\x12\x15\n\x04name\x18\x01 \x01(\tB\x07\xfa\x42\x04r\x02\x10\x01\x12\x34\n\x0ctyped_config\x18\x02 \x01(\x0b\x32\x14.google.protobuf.AnyB\x08\xfa\x42\x05\xa2\x01\x02\x08\x01\x42N\n\x16\x63om.github.xds.core.v3B\x0e\x45xtensionProtoP\x01Z\"github.com/cncf/xds/go/xds/core/v3b\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Xds
		module Core
				module V3
						TypedExtensionConfig = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("xds.core.v3.TypedExtensionConfig").msgclass
				end
		end
end
