# frozen_string_literal: true

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: envoy/config/core/v3/http_service.proto

require "google/protobuf"

require "envoy/config/core/v3/base_pb"
require "envoy/config/core/v3/http_uri_pb"
require "udpa/annotations/status_pb"
require "validate/validate_pb"


descriptor_data = "\n\'envoy/config/core/v3/http_service.proto\x12\x14\x65nvoy.config.core.v3\x1a\x1f\x65nvoy/config/core/v3/base.proto\x1a#envoy/config/core/v3/http_uri.proto\x1a\x1dudpa/annotations/status.proto\x1a\x17validate/validate.proto\"\x92\x01\n\x0bHttpService\x12/\n\x08http_uri\x18\x01 \x01(\x0b\x32\x1d.envoy.config.core.v3.HttpUri\x12R\n\x16request_headers_to_add\x18\x02 \x03(\x0b\x32\'.envoy.config.core.v3.HeaderValueOptionB\t\xfa\x42\x06\x92\x01\x03\x10\xe8\x07\x42\x84\x01\n\"io.envoyproxy.envoy.config.core.v3B\x10HttpServiceProtoP\x01ZBgithub.com/envoyproxy/go-control-plane/envoy/config/core/v3;corev3\xba\x80\xc8\xd1\x06\x02\x10\x02\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Envoy
		module Config
				module Core
						module V3
								HttpService = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.config.core.v3.HttpService").msgclass
						end
				end
		end
end
