# frozen_string_literal: true

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: envoy/config/core/v3/proxy_protocol.proto

require "google/protobuf"

require "envoy/config/core/v3/substitution_format_string_pb"
require "udpa/annotations/status_pb"
require "validate/validate_pb"


descriptor_data = "\n)envoy/config/core/v3/proxy_protocol.proto\x12\x14\x65nvoy.config.core.v3\x1a\x35\x65nvoy/config/core/v3/substitution_format_string.proto\x1a\x1dudpa/annotations/status.proto\x1a\x17validate/validate.proto\"\xcc\x01\n\x1cProxyProtocolPassThroughTLVs\x12X\n\nmatch_type\x18\x01 \x01(\x0e\x32\x44.envoy.config.core.v3.ProxyProtocolPassThroughTLVs.PassTLVsMatchType\x12\x1f\n\x08tlv_type\x18\x02 \x03(\rB\r\xfa\x42\n\x92\x01\x07\"\x05*\x03\x10\x80\x02\"1\n\x11PassTLVsMatchType\x12\x0f\n\x0bINCLUDE_ALL\x10\x00\x12\x0b\n\x07INCLUDE\x10\x01\"x\n\x08TlvEntry\x12\x16\n\x04type\x18\x01 \x01(\rB\x08\xfa\x42\x05*\x03\x10\x80\x02\x12\r\n\x05value\x18\x02 \x01(\x0c\x12\x45\n\rformat_string\x18\x03 \x01(\x0b\x32..envoy.config.core.v3.SubstitutionFormatString\"\xf7\x01\n\x13ProxyProtocolConfig\x12\x42\n\x07version\x18\x01 \x01(\x0e\x32\x31.envoy.config.core.v3.ProxyProtocolConfig.Version\x12M\n\x11pass_through_tlvs\x18\x02 \x01(\x0b\x32\x32.envoy.config.core.v3.ProxyProtocolPassThroughTLVs\x12\x32\n\nadded_tlvs\x18\x03 \x03(\x0b\x32\x1e.envoy.config.core.v3.TlvEntry\"\x19\n\x07Version\x12\x06\n\x02V1\x10\x00\x12\x06\n\x02V2\x10\x01\"C\n\rPerHostConfig\x12\x32\n\nadded_tlvs\x18\x01 \x03(\x0b\x32\x1e.envoy.config.core.v3.TlvEntryB\x86\x01\n\"io.envoyproxy.envoy.config.core.v3B\x12ProxyProtocolProtoP\x01ZBgithub.com/envoyproxy/go-control-plane/envoy/config/core/v3;corev3\xba\x80\xc8\xd1\x06\x02\x10\x02\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Envoy
		module Config
				module Core
						module V3
								ProxyProtocolPassThroughTLVs = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.config.core.v3.ProxyProtocolPassThroughTLVs").msgclass
								ProxyProtocolPassThroughTLVs::PassTLVsMatchType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.config.core.v3.ProxyProtocolPassThroughTLVs.PassTLVsMatchType").enummodule
								TlvEntry = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.config.core.v3.TlvEntry").msgclass
								ProxyProtocolConfig = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.config.core.v3.ProxyProtocolConfig").msgclass
								ProxyProtocolConfig::Version = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.config.core.v3.ProxyProtocolConfig.Version").enummodule
								PerHostConfig = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.config.core.v3.PerHostConfig").msgclass
						end
				end
		end
end
