# frozen_string_literal: true

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: envoy/config/core/v3/socket_option.proto

require "google/protobuf"

require "udpa/annotations/status_pb"
require "udpa/annotations/versioning_pb"
require "validate/validate_pb"


descriptor_data = "\n(envoy/config/core/v3/socket_option.proto\x12\x14\x65nvoy.config.core.v3\x1a\x1dudpa/annotations/status.proto\x1a!udpa/annotations/versioning.proto\x1a\x17validate/validate.proto\"\xa2\x04\n\x0cSocketOption\x12\x13\n\x0b\x64\x65scription\x18\x01 \x01(\t\x12\r\n\x05level\x18\x02 \x01(\x03\x12\x0c\n\x04name\x18\x03 \x01(\x03\x12\x13\n\tint_value\x18\x04 \x01(\x03H\x00\x12\x13\n\tbuf_value\x18\x05 \x01(\x0cH\x00\x12G\n\x05state\x18\x06 \x01(\x0e\x32..envoy.config.core.v3.SocketOption.SocketStateB\x08\xfa\x42\x05\x82\x01\x02\x10\x01\x12;\n\x04type\x18\x07 \x01(\x0b\x32-.envoy.config.core.v3.SocketOption.SocketType\x1a\xb2\x01\n\nSocketType\x12\x44\n\x06stream\x18\x01 \x01(\x0b\x32\x34.envoy.config.core.v3.SocketOption.SocketType.Stream\x12H\n\x08\x64\x61tagram\x18\x02 \x01(\x0b\x32\x36.envoy.config.core.v3.SocketOption.SocketType.Datagram\x1a\x08\n\x06Stream\x1a\n\n\x08\x44\x61tagram\"F\n\x0bSocketState\x12\x11\n\rSTATE_PREBIND\x10\x00\x12\x0f\n\x0bSTATE_BOUND\x10\x01\x12\x13\n\x0fSTATE_LISTENING\x10\x02:%\x9a\xc5\x88\x1e \n\x1e\x65nvoy.api.v2.core.SocketOptionB\x0c\n\x05value\x12\x03\xf8\x42\x01\"S\n\x15SocketOptionsOverride\x12:\n\x0esocket_options\x18\x01 \x03(\x0b\x32\".envoy.config.core.v3.SocketOptionB\x85\x01\n\"io.envoyproxy.envoy.config.core.v3B\x11SocketOptionProtoP\x01ZBgithub.com/envoyproxy/go-control-plane/envoy/config/core/v3;corev3\xba\x80\xc8\xd1\x06\x02\x10\x02\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Envoy
		module Config
				module Core
						module V3
								SocketOption = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.config.core.v3.SocketOption").msgclass
								SocketOption::SocketType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.config.core.v3.SocketOption.SocketType").msgclass
								SocketOption::SocketType::Stream = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.config.core.v3.SocketOption.SocketType.Stream").msgclass
								SocketOption::SocketType::Datagram = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.config.core.v3.SocketOption.SocketType.Datagram").msgclass
								SocketOption::SocketState = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.config.core.v3.SocketOption.SocketState").enummodule
								SocketOptionsOverride = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.config.core.v3.SocketOptionsOverride").msgclass
						end
				end
		end
end
