# frozen_string_literal: true

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: envoy/config/core/v3/socket_cmsg_headers.proto

require "google/protobuf"

require "google/protobuf/wrappers_pb"
require "udpa/annotations/status_pb"


descriptor_data = "\n.envoy/config/core/v3/socket_cmsg_headers.proto\x12\x14\x65nvoy.config.core.v3\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1dudpa/annotations/status.proto\"\x83\x01\n\x11SocketCmsgHeaders\x12+\n\x05level\x18\x01 \x01(\x0b\x32\x1c.google.protobuf.UInt32Value\x12*\n\x04type\x18\x02 \x01(\x0b\x32\x1c.google.protobuf.UInt32Value\x12\x15\n\rexpected_size\x18\x03 \x01(\rB\x8a\x01\n\"io.envoyproxy.envoy.config.core.v3B\x16SocketCmsgHeadersProtoP\x01ZBgithub.com/envoyproxy/go-control-plane/envoy/config/core/v3;corev3\xba\x80\xc8\xd1\x06\x02\x10\x02\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Envoy
		module Config
				module Core
						module V3
								SocketCmsgHeaders = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.config.core.v3.SocketCmsgHeaders").msgclass
						end
				end
		end
end
