# frozen_string_literal: true

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: envoy/type/v3/ratelimit_strategy.proto

require "google/protobuf"

require "envoy/type/v3/ratelimit_unit_pb"
require "envoy/type/v3/token_bucket_pb"
require "xds/annotations/v3/status_pb"
require "udpa/annotations/status_pb"
require "validate/validate_pb"


descriptor_data = "\n&envoy/type/v3/ratelimit_strategy.proto\x12\renvoy.type.v3\x1a\"envoy/type/v3/ratelimit_unit.proto\x1a envoy/type/v3/token_bucket.proto\x1a\x1fxds/annotations/v3/status.proto\x1a\x1dudpa/annotations/status.proto\x1a\x17validate/validate.proto\"\x9e\x03\n\x11RateLimitStrategy\x12N\n\x0c\x62lanket_rule\x18\x01 \x01(\x0e\x32,.envoy.type.v3.RateLimitStrategy.BlanketRuleB\x08\xfa\x42\x05\x82\x01\x02\x10\x01H\x00\x12V\n\x16requests_per_time_unit\x18\x02 \x01(\x0b\x32\x34.envoy.type.v3.RateLimitStrategy.RequestsPerTimeUnitH\x00\x12\x32\n\x0ctoken_bucket\x18\x03 \x01(\x0b\x32\x1a.envoy.type.v3.TokenBucketH\x00\x1ap\n\x13RequestsPerTimeUnit\x12\x1e\n\x16requests_per_time_unit\x18\x01 \x01(\x04\x12\x39\n\ttime_unit\x18\x02 \x01(\x0e\x32\x1c.envoy.type.v3.RateLimitUnitB\x08\xfa\x42\x05\x82\x01\x02\x10\x01\"*\n\x0b\x42lanketRule\x12\r\n\tALLOW_ALL\x10\x00\x12\x0c\n\x08\x44\x45NY_ALL\x10\x01\x42\x0f\n\x08strategy\x12\x03\xf8\x42\x01\x42\x84\x01\n\x1bio.envoyproxy.envoy.type.v3B\x16RatelimitStrategyProtoP\x01Z;github.com/envoyproxy/go-control-plane/envoy/type/v3;typev3\xba\x80\xc8\xd1\x06\x02\x10\x02\xd2\xc6\xa4\xe1\x06\x02\x08\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Envoy
		module Type
				module V3
						RateLimitStrategy = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.type.v3.RateLimitStrategy").msgclass
						RateLimitStrategy::RequestsPerTimeUnit = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.type.v3.RateLimitStrategy.RequestsPerTimeUnit").msgclass
						RateLimitStrategy::BlanketRule = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.type.v3.RateLimitStrategy.BlanketRule").enummodule
				end
		end
end
