# frozen_string_literal: true

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: xds/type/matcher/v3/ip.proto

require "google/protobuf"

require "xds/annotations/v3/status_pb"
require "xds/core/v3/cidr_pb"
require "xds/type/matcher/v3/matcher_pb"
require "validate/validate_pb"


descriptor_data = "\n\x1cxds/type/matcher/v3/ip.proto\x12\x13xds.type.matcher.v3\x1a\x1fxds/annotations/v3/status.proto\x1a\x16xds/core/v3/cidr.proto\x1a!xds/type/matcher/v3/matcher.proto\x1a\x17validate/validate.proto\"\xe2\x01\n\tIPMatcher\x12\x45\n\x0erange_matchers\x18\x01 \x03(\x0b\x32-.xds.type.matcher.v3.IPMatcher.IPRangeMatcher\x1a\x8d\x01\n\x0eIPRangeMatcher\x12\x30\n\x06ranges\x18\x01 \x03(\x0b\x32\x16.xds.core.v3.CidrRangeB\x08\xfa\x42\x05\x92\x01\x02\x08\x01\x12\x36\n\x08on_match\x18\x02 \x01(\x0b\x32$.xds.type.matcher.v3.Matcher.OnMatch\x12\x11\n\texclusive\x18\x03 \x01(\x08\x42\x66\n\x1e\x63om.github.xds.type.matcher.v3B\x0eIPMatcherProtoP\x01Z*github.com/cncf/xds/go/xds/type/matcher/v3\xd2\xc6\xa4\xe1\x06\x02\x08\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Xds
		module Type
				module Matcher
						module V3
								IPMatcher = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("xds.type.matcher.v3.IPMatcher").msgclass
								IPMatcher::IPRangeMatcher = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("xds.type.matcher.v3.IPMatcher.IPRangeMatcher").msgclass
						end
				end
		end
end
