# frozen_string_literal: true

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: xds/type/matcher/v3/range.proto

require "google/protobuf"

require "xds/type/v3/range_pb"
require "xds/type/matcher/v3/matcher_pb"
require "validate/validate_pb"


descriptor_data = "\n\x1fxds/type/matcher/v3/range.proto\x12\x13xds.type.matcher.v3\x1a\x17xds/type/v3/range.proto\x1a!xds/type/matcher/v3/matcher.proto\x1a\x17validate/validate.proto\"\xdb\x01\n\x11Int64RangeMatcher\x12K\n\x0erange_matchers\x18\x01 \x03(\x0b\x32\x33.xds.type.matcher.v3.Int64RangeMatcher.RangeMatcher\x1ay\n\x0cRangeMatcher\x12\x31\n\x06ranges\x18\x01 \x03(\x0b\x32\x17.xds.type.v3.Int64RangeB\x08\xfa\x42\x05\x92\x01\x02\x08\x01\x12\x36\n\x08on_match\x18\x02 \x01(\x0b\x32$.xds.type.matcher.v3.Matcher.OnMatch\"\xdb\x01\n\x11Int32RangeMatcher\x12K\n\x0erange_matchers\x18\x01 \x03(\x0b\x32\x33.xds.type.matcher.v3.Int32RangeMatcher.RangeMatcher\x1ay\n\x0cRangeMatcher\x12\x31\n\x06ranges\x18\x01 \x03(\x0b\x32\x17.xds.type.v3.Int32RangeB\x08\xfa\x42\x05\x92\x01\x02\x08\x01\x12\x36\n\x08on_match\x18\x02 \x01(\x0b\x32$.xds.type.matcher.v3.Matcher.OnMatch\"\xde\x01\n\x12\x44oubleRangeMatcher\x12L\n\x0erange_matchers\x18\x01 \x03(\x0b\x32\x34.xds.type.matcher.v3.DoubleRangeMatcher.RangeMatcher\x1az\n\x0cRangeMatcher\x12\x32\n\x06ranges\x18\x01 \x03(\x0b\x32\x18.xds.type.v3.DoubleRangeB\x08\xfa\x42\x05\x92\x01\x02\x08\x01\x12\x36\n\x08on_match\x18\x02 \x01(\x0b\x32$.xds.type.matcher.v3.Matcher.OnMatchBZ\n\x1e\x63om.github.xds.type.matcher.v3B\nRangeProtoP\x01Z*github.com/cncf/xds/go/xds/type/matcher/v3b\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Xds
		module Type
				module Matcher
						module V3
								Int64RangeMatcher = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("xds.type.matcher.v3.Int64RangeMatcher").msgclass
								Int64RangeMatcher::RangeMatcher = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("xds.type.matcher.v3.Int64RangeMatcher.RangeMatcher").msgclass
								Int32RangeMatcher = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("xds.type.matcher.v3.Int32RangeMatcher").msgclass
								Int32RangeMatcher::RangeMatcher = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("xds.type.matcher.v3.Int32RangeMatcher.RangeMatcher").msgclass
								DoubleRangeMatcher = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("xds.type.matcher.v3.DoubleRangeMatcher").msgclass
								DoubleRangeMatcher::RangeMatcher = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("xds.type.matcher.v3.DoubleRangeMatcher.RangeMatcher").msgclass
						end
				end
		end
end
