# frozen_string_literal: true

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: xds/type/matcher/v3/regex.proto

require "google/protobuf"

require "validate/validate_pb"


descriptor_data = "\n\x1fxds/type/matcher/v3/regex.proto\x12\x13xds.type.matcher.v3\x1a\x17validate/validate.proto\"\x94\x01\n\x0cRegexMatcher\x12K\n\ngoogle_re2\x18\x01 \x01(\x0b\x32+.xds.type.matcher.v3.RegexMatcher.GoogleRE2B\x08\xfa\x42\x05\x8a\x01\x02\x10\x01H\x00\x12\x16\n\x05regex\x18\x02 \x01(\tB\x07\xfa\x42\x04r\x02\x10\x01\x1a\x0b\n\tGoogleRE2B\x12\n\x0b\x65ngine_type\x12\x03\xf8\x42\x01\x42Z\n\x1e\x63om.github.xds.type.matcher.v3B\nRegexProtoP\x01Z*github.com/cncf/xds/go/xds/type/matcher/v3b\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Xds
		module Type
				module Matcher
						module V3
								RegexMatcher = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("xds.type.matcher.v3.RegexMatcher").msgclass
								RegexMatcher::GoogleRE2 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("xds.type.matcher.v3.RegexMatcher.GoogleRE2").msgclass
						end
				end
		end
end
