FROM ruby:latest

WORKDIR /app
ENV BUNDLE_GEMFILE=/app/gems.rb \
    BUNDLE_WITHOUT=maintenance

# Install dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# Copy gemfile, gemspec, and minimal lib files needed for gemspec.
COPY gems.rb *.gemspec ./
COPY lib/async/grpc/xds/version.rb lib/async/grpc/xds/version.rb
RUN bundle install

# Copy application code
COPY . .

# Expose port
EXPOSE ${PORT:-50051}

# Run gRPC server
CMD bundle exec ruby integration/client/backend_server.rb
