# frozen_string_literal: true

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: udpa/annotations/security.proto

require "google/protobuf"

require "udpa/annotations/status_pb"
require "google/protobuf/any_pb"
require "google/protobuf/descriptor_pb"
require "validate/validate_pb"


descriptor_data = "\n\x1fudpa/annotations/security.proto\x12\x10udpa.annotations\x1a\x1dudpa/annotations/status.proto\x1a\x19google/protobuf/any.proto\x1a google/protobuf/descriptor.proto\x1a\x17validate/validate.proto\"o\n\x17\x46ieldSecurityAnnotation\x12*\n\"configure_for_untrusted_downstream\x18\x01 \x01(\x08\x12(\n configure_for_untrusted_upstream\x18\x02 \x01(\x08:]\n\x08security\x12\x1d.google.protobuf.FieldOptions\x18\xb1\xf2\xa6\x05 \x01(\x0b\x32).udpa.annotations.FieldSecurityAnnotationB\x08\xba\x80\xc8\xd1\x06\x02\x08\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Udpa
		module Annotations
				FieldSecurityAnnotation = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("udpa.annotations.FieldSecurityAnnotation").msgclass
		end
end
