# frozen_string_literal: true

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: udpa/annotations/status.proto

require "google/protobuf"

require "google/protobuf/descriptor_pb"


descriptor_data = "\n\x1dudpa/annotations/status.proto\x12\x10udpa.annotations\x1a google/protobuf/descriptor.proto\"t\n\x10StatusAnnotation\x12\x18\n\x10work_in_progress\x18\x01 \x01(\x08\x12\x46\n\x16package_version_status\x18\x02 \x01(\x0e\x32&.udpa.annotations.PackageVersionStatus*]\n\x14PackageVersionStatus\x12\x0b\n\x07UNKNOWN\x10\x00\x12\n\n\x06\x46ROZEN\x10\x01\x12\n\n\x06\x41\x43TIVE\x10\x02\x12 \n\x1cNEXT_MAJOR_VERSION_CANDIDATE\x10\x03:X\n\x0b\x66ile_status\x12\x1c.google.protobuf.FileOptions\x18\x87\x80\x99j \x01(\x0b\x32\".udpa.annotations.StatusAnnotationb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Udpa
		module Annotations
				StatusAnnotation = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("udpa.annotations.StatusAnnotation").msgclass
				PackageVersionStatus = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("udpa.annotations.PackageVersionStatus").enummodule
		end
end
