# frozen_string_literal: true

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: udpa/annotations/versioning.proto

require "google/protobuf"

require "google/protobuf/descriptor_pb"


descriptor_data = "\n!udpa/annotations/versioning.proto\x12\x10udpa.annotations\x1a google/protobuf/descriptor.proto\"5\n\x14VersioningAnnotation\x12\x1d\n\x15previous_message_type\x18\x01 \x01(\t:^\n\nversioning\x12\x1f.google.protobuf.MessageOptions\x18\xd3\x88\xe1\x03 \x01(\x0b\x32&.udpa.annotations.VersioningAnnotationb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Udpa
		module Annotations
				VersioningAnnotation = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("udpa.annotations.VersioningAnnotation").msgclass
		end
end
