# frozen_string_literal: true

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: envoy/type/metadata/v3/metadata.proto

require "google/protobuf"

require "udpa/annotations/status_pb"
require "udpa/annotations/versioning_pb"
require "validate/validate_pb"


descriptor_data = "\n%envoy/type/metadata/v3/metadata.proto\x12\x16\x65nvoy.type.metadata.v3\x1a\x1dudpa/annotations/status.proto\x1a!udpa/annotations/versioning.proto\x1a\x17validate/validate.proto\"\x85\x02\n\x0bMetadataKey\x12\x14\n\x03key\x18\x01 \x01(\tB\x07\xfa\x42\x04r\x02\x10\x01\x12G\n\x04path\x18\x02 \x03(\x0b\x32/.envoy.type.metadata.v3.MetadataKey.PathSegmentB\x08\xfa\x42\x05\x92\x01\x02\x08\x01\x1al\n\x0bPathSegment\x12\x16\n\x03key\x18\x01 \x01(\tB\x07\xfa\x42\x04r\x02\x10\x01H\x00:5\x9a\xc5\x88\x1e\x30\n.envoy.type.metadata.v2.MetadataKey.PathSegmentB\x0e\n\x07segment\x12\x03\xf8\x42\x01:)\x9a\xc5\x88\x1e$\n\"envoy.type.metadata.v2.MetadataKey\"\xb3\x04\n\x0cMetadataKind\x12?\n\x07request\x18\x01 \x01(\x0b\x32,.envoy.type.metadata.v3.MetadataKind.RequestH\x00\x12;\n\x05route\x18\x02 \x01(\x0b\x32*.envoy.type.metadata.v3.MetadataKind.RouteH\x00\x12?\n\x07\x63luster\x18\x03 \x01(\x0b\x32,.envoy.type.metadata.v3.MetadataKind.ClusterH\x00\x12\x39\n\x04host\x18\x04 \x01(\x0b\x32).envoy.type.metadata.v3.MetadataKind.HostH\x00\x1a=\n\x07Request:2\x9a\xc5\x88\x1e-\n+envoy.type.metadata.v2.MetadataKind.Request\x1a\x39\n\x05Route:0\x9a\xc5\x88\x1e+\n)envoy.type.metadata.v2.MetadataKind.Route\x1a=\n\x07\x43luster:2\x9a\xc5\x88\x1e-\n+envoy.type.metadata.v2.MetadataKind.Cluster\x1a\x37\n\x04Host:/\x9a\xc5\x88\x1e*\n(envoy.type.metadata.v2.MetadataKind.Host:*\x9a\xc5\x88\x1e%\n#envoy.type.metadata.v2.MetadataKindB\x0b\n\x04kind\x12\x03\xf8\x42\x01\x42\x89\x01\n$io.envoyproxy.envoy.type.metadata.v3B\rMetadataProtoP\x01ZHgithub.com/envoyproxy/go-control-plane/envoy/type/metadata/v3;metadatav3\xba\x80\xc8\xd1\x06\x02\x10\x02\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Envoy
		module Type
				module Metadata
						module V3
								MetadataKey = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.type.metadata.v3.MetadataKey").msgclass
								MetadataKey::PathSegment = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.type.metadata.v3.MetadataKey.PathSegment").msgclass
								MetadataKind = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.type.metadata.v3.MetadataKind").msgclass
								MetadataKind::Request = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.type.metadata.v3.MetadataKind.Request").msgclass
								MetadataKind::Route = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.type.metadata.v3.MetadataKind.Route").msgclass
								MetadataKind::Cluster = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.type.metadata.v3.MetadataKind.Cluster").msgclass
								MetadataKind::Host = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.type.metadata.v3.MetadataKind.Host").msgclass
						end
				end
		end
end
