name: Test xDS

on: [push, pull_request]

permissions:
  contents: read

env:
  CONSOLE_OUTPUT: XTerm

jobs:
  test:
    name: ${{matrix.ruby}} on ${{matrix.os}}
    runs-on: ${{matrix.os}}-latest
    continue-on-error: ${{matrix.experimental}}

    strategy:
      matrix:
        os:
          - ubuntu

        ruby:
          - "3.3"
          - "3.4"
          - "4.0"

        experimental: [false]

    steps:
    - uses: actions/checkout@v6

    - name: Run tests
      timeout-minutes: 10
      working-directory: integration/client
      env:
        RUBY_VERSION: ${{matrix.ruby}}
      run: docker compose up --build --exit-code-from tests

    - name: Test dedicated discovery services with Envoy
      timeout-minutes: 10
      working-directory: integration/envoy
      env:
        RUBY_VERSION: ${{matrix.ruby}}
      run: docker compose up --build --exit-code-from tests
