# frozen_string_literal: true

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: envoy/type/matcher/v3/address.proto

require "google/protobuf"

require "xds/core/v3/cidr_pb"
require "udpa/annotations/status_pb"


descriptor_data = "\n#envoy/type/matcher/v3/address.proto\x12\x15\x65nvoy.type.matcher.v3\x1a\x16xds/core/v3/cidr.proto\x1a\x1dudpa/annotations/status.proto\"8\n\x0e\x41\x64\x64ressMatcher\x12&\n\x06ranges\x18\x01 \x03(\x0b\x32\x16.xds.core.v3.CidrRangeB\x85\x01\n#io.envoyproxy.envoy.type.matcher.v3B\x0c\x41\x64\x64ressProtoP\x01ZFgithub.com/envoyproxy/go-control-plane/envoy/type/matcher/v3;matcherv3\xba\x80\xc8\xd1\x06\x02\x10\x02\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Envoy
		module Type
				module Matcher
						module V3
								AddressMatcher = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.type.matcher.v3.AddressMatcher").msgclass
						end
				end
		end
end
