# frozen_string_literal: true

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: envoy/type/matcher/v3/http_inputs.proto

require "google/protobuf"

require "udpa/annotations/status_pb"
require "validate/validate_pb"


descriptor_data = "\n\'envoy/type/matcher/v3/http_inputs.proto\x12\x15\x65nvoy.type.matcher.v3\x1a\x1dudpa/annotations/status.proto\x1a\x17validate/validate.proto\"?\n\x1bHttpRequestHeaderMatchInput\x12 \n\x0bheader_name\x18\x01 \x01(\tB\x0b\xfa\x42\x08r\x06\xc0\x01\x01\xc8\x01\x00\"@\n\x1cHttpRequestTrailerMatchInput\x12 \n\x0bheader_name\x18\x01 \x01(\tB\x0b\xfa\x42\x08r\x06\xc0\x01\x01\xc8\x01\x00\"@\n\x1cHttpResponseHeaderMatchInput\x12 \n\x0bheader_name\x18\x01 \x01(\tB\x0b\xfa\x42\x08r\x06\xc0\x01\x01\xc8\x01\x00\"A\n\x1dHttpResponseTrailerMatchInput\x12 \n\x0bheader_name\x18\x01 \x01(\tB\x0b\xfa\x42\x08r\x06\xc0\x01\x01\xc8\x01\x00\"?\n\x1fHttpRequestQueryParamMatchInput\x12\x1c\n\x0bquery_param\x18\x01 \x01(\tB\x07\xfa\x42\x04r\x02\x10\x01\x42\x88\x01\n#io.envoyproxy.envoy.type.matcher.v3B\x0fHttpInputsProtoP\x01ZFgithub.com/envoyproxy/go-control-plane/envoy/type/matcher/v3;matcherv3\xba\x80\xc8\xd1\x06\x02\x10\x02\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Envoy
		module Type
				module Matcher
						module V3
								HttpRequestHeaderMatchInput = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.type.matcher.v3.HttpRequestHeaderMatchInput").msgclass
								HttpRequestTrailerMatchInput = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.type.matcher.v3.HttpRequestTrailerMatchInput").msgclass
								HttpResponseHeaderMatchInput = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.type.matcher.v3.HttpResponseHeaderMatchInput").msgclass
								HttpResponseTrailerMatchInput = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.type.matcher.v3.HttpResponseTrailerMatchInput").msgclass
								HttpRequestQueryParamMatchInput = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.type.matcher.v3.HttpRequestQueryParamMatchInput").msgclass
						end
				end
		end
end
