# frozen_string_literal: true

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: envoy/type/matcher/v3/regex.proto

require "google/protobuf"

require "google/protobuf/wrappers_pb"
require "envoy/annotations/deprecation_pb"
require "udpa/annotations/status_pb"
require "udpa/annotations/versioning_pb"
require "validate/validate_pb"


descriptor_data = "\n!envoy/type/matcher/v3/regex.proto\x12\x15\x65nvoy.type.matcher.v3\x1a\x1egoogle/protobuf/wrappers.proto\x1a#envoy/annotations/deprecation.proto\x1a\x1dudpa/annotations/status.proto\x1a!udpa/annotations/versioning.proto\x1a\x17validate/validate.proto\"\xb4\x02\n\x0cRegexMatcher\x12P\n\ngoogle_re2\x18\x01 \x01(\x0b\x32-.envoy.type.matcher.v3.RegexMatcher.GoogleRE2B\x0b\x18\x01\x92\xc7\x86\xd8\x04\x03\x33.0H\x00\x12\x16\n\x05regex\x18\x02 \x01(\tB\x07\xfa\x42\x04r\x02\x10\x01\x1a\x82\x01\n\tGoogleRE2\x12\x43\n\x10max_program_size\x18\x01 \x01(\x0b\x32\x1c.google.protobuf.UInt32ValueB\x0b\x18\x01\x92\xc7\x86\xd8\x04\x03\x33.0:0\x9a\xc5\x88\x1e+\n)envoy.type.matcher.RegexMatcher.GoogleRE2:&\x9a\xc5\x88\x1e!\n\x1f\x65nvoy.type.matcher.RegexMatcherB\r\n\x0b\x65ngine_type\"\xaf\x01\n\x17RegexMatchAndSubstitute\x12>\n\x07pattern\x18\x01 \x01(\x0b\x32#.envoy.type.matcher.v3.RegexMatcherB\x08\xfa\x42\x05\x8a\x01\x02\x10\x01\x12!\n\x0csubstitution\x18\x02 \x01(\tB\x0b\xfa\x42\x08r\x06\xc0\x01\x02\xc8\x01\x00:1\x9a\xc5\x88\x1e,\n*envoy.type.matcher.RegexMatchAndSubstituteB\x83\x01\n#io.envoyproxy.envoy.type.matcher.v3B\nRegexProtoP\x01ZFgithub.com/envoyproxy/go-control-plane/envoy/type/matcher/v3;matcherv3\xba\x80\xc8\xd1\x06\x02\x10\x02\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Envoy
		module Type
				module Matcher
						module V3
								RegexMatcher = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.type.matcher.v3.RegexMatcher").msgclass
								RegexMatcher::GoogleRE2 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.type.matcher.v3.RegexMatcher.GoogleRE2").msgclass
								RegexMatchAndSubstitute = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.type.matcher.v3.RegexMatchAndSubstitute").msgclass
						end
				end
		end
end
