# frozen_string_literal: true

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: envoy/type/matcher/v3/status_code_input.proto

require "google/protobuf"

require "udpa/annotations/status_pb"


descriptor_data = "\n-envoy/type/matcher/v3/status_code_input.proto\x12\x15\x65nvoy.type.matcher.v3\x1a\x1dudpa/annotations/status.proto\"\"\n HttpResponseStatusCodeMatchInput\"\'\n%HttpResponseStatusCodeClassMatchInputB\x8d\x01\n#io.envoyproxy.envoy.type.matcher.v3B\x14StatusCodeInputProtoP\x01ZFgithub.com/envoyproxy/go-control-plane/envoy/type/matcher/v3;matcherv3\xba\x80\xc8\xd1\x06\x02\x10\x02\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Envoy
		module Type
				module Matcher
						module V3
								HttpResponseStatusCodeMatchInput = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.type.matcher.v3.HttpResponseStatusCodeMatchInput").msgclass
								HttpResponseStatusCodeClassMatchInput = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("envoy.type.matcher.v3.HttpResponseStatusCodeClassMatchInput").msgclass
						end
				end
		end
end
